# PostgreSQL
#   Ensure the PostgreSQL gem is defined in your Gemfile
#   gem 'pg'
development:
  adapter: postgresql
  encoding: utf8
  database: railsbrickssample_development
  username: brandon
  host: localhost
  pool: 5
  port: 5432
  
production:
  adapter: postgresql
  encoding: utf8
  database: railsbrickssample_development
  username: brandon
  host: localhost
  pool: 5
  port: 5432
